import { TransactionType } from '../models/transaction.model';

export const CATEGORY_OPTIONS: Record<TransactionType, Record<string, readonly string[]>> = {
  Expense: {
    'Housing & Accommodation': ['Rent', 'PG / Paying Guest', 'Hostel', 'Apartment maintenance', 'Society maintenance', 'Property tax', 'Home loan EMI', 'Home insurance', 'Security deposit', 'Advance rent', 'Repairs', 'Plumbing', 'Electrical repairs', 'Carpentry', 'Painting', 'Pest control', 'Cleaning services', 'Domestic help', 'Furniture', 'Home appliances', 'Kitchen equipment', 'Home décor', 'Bedding & mattresses', 'Curtains', 'Lighting', 'Moving / relocation', 'Storage', 'Home security / CCTV', 'Locksmith', 'AC servicing', 'Appliance repair', 'Appliance servicing', 'Water purifier / RO maintenance', 'Internet installation / setup', 'Home insurance deductible / excess', 'Rental agreement charges', 'Brokerage / agent fee', 'Move-in / move-out charges', 'Home security deposit refund tracking', 'Laundry / ironing services', 'Water tanker', 'Generator / backup power', 'Inverter / UPS maintenance', 'Other housing expenses'],
    'Food & Groceries': ['Groceries', 'Rice', 'Wheat / flour', 'Pulses', 'Lentils', 'Oil', 'Spices', 'Salt / sugar', 'Vegetables', 'Fruits', 'Dairy', 'Eggs', 'Meat', 'Fish / seafood', 'Frozen foods', 'Snacks', 'Beverages', 'Packaged foods', 'Bakery items', 'Cooking ingredients', 'Household food supplies', 'Eating Out', 'Restaurants', 'Cafes', 'Fast food', 'Street food', 'Bakery / desserts', 'Food courts', 'Buffets', 'Food Delivery', 'Swiggy', 'Zomato', 'Other food delivery', 'Office meals', 'College meals', 'Tiffin / meal services', 'Tea / coffee', 'Water bottles', 'Food subscriptions', 'Tips', 'Ready-to-eat meals', 'Instant noodles', 'Sauces / condiments', 'Pickles', 'Dry fruits / nuts', 'Seeds', 'Ice cream / frozen desserts', 'Baby food', 'Drinking water cans', 'Cooking gas delivery charges', 'Food trucks', 'Cloud kitchens', 'Dessert shops', 'Juice shops', 'Ice cream shops', 'Fine dining', 'Takeaway', 'Other food expense'],
    'Transportation': ['Public Transport', 'Bus', 'Metro', 'Local train', 'Railway', 'Public transport passes', 'Personal Vehicle', 'Petrol', 'Diesel', 'CNG', 'EV charging', 'Vehicle EMI', 'Vehicle insurance', 'Vehicle registration', 'Road tax', 'PUC', 'Vehicle servicing', 'Repairs', 'Spare parts', 'Tyres', 'Battery', 'Engine oil', 'Washing', 'Detailing', 'Accessories', 'Taxi / Ride-Hailing', 'Uber', 'Ola', 'Rapido', 'Auto', 'Taxi', 'Rental vehicle', 'Parking', 'Toll', 'Fastag recharge', 'Driving licence', 'Driving lessons', 'Traffic fines', 'Transportation passes', 'Vehicle rental', 'Moving / transport charges', 'Platform charges', 'Reservation Charges', 'Insurance renewal', 'Roadside assistance', 'Parking subscription', 'Car/bike accessories', 'Number plate / registration charges', 'Vehicle cleaning supplies', 'Other transportation'],
    'Bills & Utilities': ['Electricity', 'Water', 'Gas', 'LPG cylinder', 'Piped gas', 'Garbage collection', 'Sewage', 'Mobile recharge', 'Mobile postpaid', 'Internet / broadband', 'Wi-Fi', 'Landline', 'Netflix', 'Amazon Prime', 'Disney+ / Hotstar', 'YouTube Premium', 'Spotify', 'Apple Music', 'Cloud storage', 'Google One', 'iCloud', 'Software subscriptions', 'Gaming subscriptions', 'News subscriptions', 'Other subscriptions', 'Cable TV', 'DTH', 'OTT', 'Maintenance charges', 'Internet equipment rental', 'Electricity connection charges', 'Water tanker', 'Gas delivery charges', 'Generator charges', 'Solar maintenance', 'Inverter / UPS electricity backup', 'Utility deposits', 'Late payment charges', 'AI subscriptions', 'Productivity apps', 'Password managers', 'VPN', 'Antivirus/security software', 'Design software', 'Developer tools', 'Storage subscriptions', 'Other bill'],
    'Shopping': ['Shirts', 'T-shirts', 'Pants', 'Jeans', 'Formal wear', 'Casual wear', 'Innerwear', 'Traditional wear', 'Winter wear', 'Sportswear', 'Shoes', 'Sandals', 'Slippers', 'Sports shoes', 'Mobile phones', 'Laptop', 'Tablet', 'Monitor', 'Keyboard', 'Mouse', 'Headphones / earphones', 'Chargers', 'Power banks', 'Cables', 'Smartwatch', 'Camera', 'Electronics accessories', 'Kitchenware', 'Cookware', 'Storage', 'Cleaning supplies', 'Décor', 'Bags', 'Wallets', 'Watches', 'Jewellery', 'Gifts', 'Toys', 'Online shopping', 'Offline shopping', 'Delivery charges', 'Other shopping'],
    'Healthcare & Medical': ['Doctor consultation', 'Hospital', 'Emergency treatment', 'Surgery', 'Medical tests', 'Diagnostic tests', 'Dental', 'Eye care', 'Physiotherapy', 'Prescription medicines', 'OTC medicines', 'Vitamins', 'First-aid supplies', 'Gym', 'Fitness classes', 'Health checkup', 'Mental wellness', 'Therapy / counselling', 'Medical equipment', 'Health devices', 'Health insurance premium', 'Family health insurance', 'Medical insurance', 'Hospital admission', 'Room charges', 'Nursing charges', 'Ambulance', 'Specialist consultation', 'Laboratory tests', 'Imaging / scans', 'Blood tests', 'Vaccinations', 'Pharmacy delivery', 'Medical consumables'],
    'Education & Learning': ['College fees', 'School fees', 'Tuition', 'Coaching', 'Online courses', 'Offline courses', 'Certifications', 'Exam fees', 'Books', 'E-books', 'Study materials', 'Stationery', 'Lab fees', 'Training', 'Workshops', 'Seminars', 'Conferences', 'Educational software', 'Learning subscriptions', 'Skill development', 'Professional certifications'],
    'Work & Professional': ['Laptop / computer', 'Monitor', 'Keyboard / mouse', 'Electronics equipment', 'Development boards', 'Sensors', 'Components', 'Tools', 'Software', 'IDE subscriptions', 'Cloud services', 'Domain', 'Hosting', 'Professional memberships', 'Conferences', 'Business travel', 'Office supplies', 'Printing', 'Photocopying', 'Stationery', 'Work-from-home equipment', 'Internet for work', 'Professional courses', 'Professional certifications', 'Job application expenses', 'Interview travel', 'Recruitment fees', 'Portfolio / website', 'Professional services'],
    'Entertainment & Recreation': ['Movies', 'Theatre', 'Streaming', 'Music', 'Concerts', 'Live shows', 'Gaming', 'Games', 'In-game purchases', 'Gaming subscriptions', 'Gaming equipment', 'Events', 'Amusement parks', 'Theme parks', 'Sports activities', 'Bowling', 'Gaming zones', 'Photography', 'Art', 'Books for leisure', 'Outings', 'Parties', 'Clubs', 'Social events', 'Café outings'],
    'Personal Care': ['Haircut', 'Hair styling', 'Salon', 'Shaving', 'Beard grooming', 'Spa', 'Soap', 'Shampoo', 'Toothpaste', 'Toothbrush', 'Deodorant', 'Perfume', 'Skincare', 'Cosmetics', 'Sanitary products', 'Towels', 'Razors', 'Grooming equipment', 'Personal accessories'],
    'Travel & Vacation': ['Flight', 'Train', 'Bus', 'Taxi', 'Rental car', 'Rental bike', 'Hotel', 'Hostel', 'Resort', 'Airbnb', 'Guest house', 'Food during travel', 'Local transportation', 'Parking', 'Toll', 'Travel insurance', 'Visa', 'Passport', 'Travel documentation', 'Tourist fees', 'Luggage', 'Travel accessories', 'Sightseeing', 'Attractions', 'Tours', 'Adventure activities', 'Events', 'Souvenirs', 'Travel shopping', 'Currency exchange fees', 'Trip cancellation fees'],
    'Family & Dependents': ['Parents', 'Children', 'Spouse', 'Siblings', 'Family groceries', 'Family medical expenses', 'Family education', 'Family transportation', 'Family bills', 'Family support', 'Allowance', 'Gifts', 'Family functions', 'Family travel', 'Household support'],
    'Financial Expenses': ['Bank charges', 'Account fees', 'ATM fees', 'Cash withdrawal charges', 'Cheque charges', 'Transfer fees', 'UPI-related charges', 'International transaction fees', 'Personal loan EMI', 'Home loan EMI', 'Vehicle loan EMI', 'Education loan EMI', 'Credit card payment', 'BNPL payment', 'Loan interest', 'Credit card interest', 'Late payment fee', 'Loan processing fee', 'Prepayment charges', 'Life insurance', 'Health insurance', 'Vehicle insurance', 'Home insurance', 'Travel insurance', 'Other insurance', 'Income tax', 'Advance tax', 'Property tax', 'Professional tax', 'Other taxes'],
    'Investments & Wealth Building': ['Stocks', 'Mutual funds', 'SIP', 'ETFs', 'Bonds', 'Government securities', 'NPS', 'REITs', 'Gold', 'Digital gold', 'Fixed deposits', 'Recurring deposits', 'PPF', 'EPF', 'Sovereign Gold Bonds', 'Brokerage', 'Platform fees', 'Transaction charges', 'Demat charges', 'Fund expense-related charges', 'Cryptocurrency', 'P2P lending', 'Other investments'],
    'Emergency & Unexpected': ['Emergency medical expense', 'Emergency travel', 'Vehicle breakdown', 'Home emergency', 'Lost / stolen item replacement', 'Urgent repair', 'Unexpected bill', 'Emergency purchase', 'Other unexpected expense'],
    'Gifts, Donations & Contributions': ['Birthday gifts', 'Wedding gifts', 'Anniversary gifts', 'Festival gifts', 'Family gifts', 'Friend gifts', 'Donations', 'Charity', 'Religious donations', 'Community contributions', 'Crowdfunding', 'Fundraising', 'Tips', 'Alms'],
    'Pets & Animals': ['Pet food', 'Veterinary', 'Medicines', 'Vaccination', 'Grooming', 'Pet accessories', 'Pet toys', 'Pet insurance', 'Pet boarding', 'Pet training', 'Pet adoption', 'Pet sitting'],
    'Children & Baby': ['Baby food', 'Diapers', 'Baby clothing', 'Toys', 'School fees', 'Childcare', 'Babysitting', "Children's healthcare", "Children's activities", "Children's books", 'Baby equipment', 'Child insurance', 'Allowance'],
    'Religious & Cultural': ['Temple / church / mosque donations', 'Religious offerings', 'Pooja materials', 'Religious functions', 'Festival expenses', 'Cultural events', 'Religious travel', 'Ceremonies', 'Ritual expenses'],
    'Fitness & Sports': ['Gym membership', 'Sports membership', 'Personal trainer', 'Yoga', 'Swimming', 'Running', 'Cycling', 'Sports equipment', 'Sports clothing', 'Sports shoes', 'Tournament fees', 'Fitness apps', 'Fitness subscriptions'],
    'Government & Legal': ['Government fees', 'Passport', 'Visa', 'Driving licence', 'Certificates', 'Documentation', 'Stamp paper', 'Notary', 'Legal consultation', 'Court fees', 'Registration fees', 'Property registration', 'RTI / application fees', 'Other official fees'],
    'Miscellaneous': ['Uncategorized expense', 'One-time expense', 'Other expense'],
  },
  Income: {
    Employment: ['Salary', 'Bonus', 'Incentive', 'Overtime', 'Allowance', 'Reimbursement'],
    'Self-Employment': ['Freelance', 'Consulting', 'Contract work', 'Business income'],
    'Investment Income': ['Dividends', 'Interest', 'Capital gains', 'Rental income'],
    'Other Income': ['Cashback', 'Rewards', 'Refund', 'Tax refund', 'Gifts received', 'Scholarship', 'Prize money', 'Commission', 'Other income'],
  },
  Transfer: {
    'Transfers — NOT Expenses': ['Bank → Bank', 'Bank → Wallet', 'Wallet → Bank', 'Bank → Cash', 'Cash → Bank', 'Credit Card → Bank', 'Savings Account → Current Account', 'Account → Account'],
  },
  Refund: {
    'Refunds & Reimbursements': ['Shopping refund', 'Food refund', 'Travel refund', 'Medical reimbursement', 'Work reimbursement', 'Cancelled order refund', 'Subscription refund', 'Bank refund', 'Insurance claim', 'Other reimbursement'],
  },
};

export const ACCOUNTS = ['HDFC', 'SBI', 'AXIS', 'Credit Card', 'UPI Wallet'] as const;
export const PAYMENT_METHODS = ['UPI', 'Cash', 'Debit Card', 'Credit Card', 'Bank Transfer', 'Net Banking', 'Other'] as const;
